import fs from 'fs';
let content = fs.readFileSync('src/features/assistant/AssistantPage.tsx', 'utf8');

const hookRegex = /const \{\s*activeChatSession,\s*addChatMessage,\s*createNewChatSession,\s*activeDataset,\s*language,\s*t,\s*\} = useApp\(\);/;
const hookReplacement = `  const {
    activeChatSession,
    addChatMessage,
    createNewChatSession,
    activeDataset,
    language,
    t,
    saveDataStory,
    saveDashboard,
    setActiveDashboardId,
    setActiveTab,
  } = useApp();`;
content = content.replace(hookRegex, hookReplacement);

const receiveLogicRegex = /const data = await res\.json\(\);[\s\S]*?addChatMessage\(activeChatSession\.id, assistantMsg\);/;
const receiveLogicReplacement = `const data = await res.json();

      let replyContent = data.reply || (language === 'ar' ? 'تمت معالجة استفسارك التحليلي بنجاح.' : 'Analytical query analyzed.');
      let actionObj = null;

      // Extract JSON action block if present
      const jsonActionMatch = replyContent.match(/\`\`\`json\\s*([\\s\\S]+?)\\s*\`\`\`/);
      if (jsonActionMatch) {
         try {
           actionObj = JSON.parse(jsonActionMatch[1]);
           replyContent = replyContent.replace(jsonActionMatch[0], '').trim();
         } catch(e) {
           console.error("Failed to parse agent action", e);
         }
      }

      const assistantMsg: ChatMessage = {
        id: \`msg-\${Date.now() + 1}\`,
        sender: 'assistant',
        content: replyContent,
        timestamp: new Date().toISOString(),
        sqlSnippet: data.sqlQuery,
        insights: data.insights,
        suggestedChart: data.suggestedChart,
      };

      addChatMessage(activeChatSession.id, assistantMsg);

      // Execute Agent Actions
      if (actionObj) {
         if (actionObj.action === 'CREATE_REPORT' && actionObj.report) {
            const newStory = {
              id: \`story-\${Date.now()}\`,
              datasetId: activeDataset.id,
              datasetName: activeDataset.name,
              title: actionObj.report.title,
              titleAr: actionObj.report.title,
              subtitle: 'Generated by AI Agent',
              subtitleAr: 'تم التوليد بواسطة الوكيل الذكي',
              executiveSummary: actionObj.report.executiveSummary,
              executiveSummaryAr: actionObj.report.executiveSummary,
              sections: (actionObj.report.sections || []).map((s:any, i:number) => ({
                 id: \`sec-\${i}\`,
                 title: s.title,
                 titleAr: s.title,
                 narrative: s.narrative,
                 narrativeAr: s.narrative,
                 insights: s.insights || []
              })),
              recommendations: actionObj.report.recommendations || [],
              generatedAt: new Date().toISOString(),
              author: 'AI Agent Copilot'
            };
            saveDataStory(newStory);
         } else if (actionObj.action === 'CREATE_DASHBOARD' && actionObj.dashboard) {
            const newDashboard = {
              id: \`dash-\${Date.now()}\`,
              name: actionObj.dashboard.title,
              description: actionObj.dashboard.description,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
              layout: 'grid',
              widgets: (actionObj.dashboard.widgets || []).map((w:any, i:number) => ({
                id: \`w-\${Date.now()}-\${i}\`,
                type: w.type || 'bar',
                title: w.title,
                datasetId: activeDataset.id,
                config: {
                   xAxis: w.xAxis || '',
                   yAxis: w.yAxis || '',
                   aggregation: 'sum'
                }
              }))
            };
            saveDashboard(newDashboard as any); // Cast as any if type complains
            setActiveDashboardId(newDashboard.id);
         }
         
         if (actionObj.tab) {
           setTimeout(() => {
             setActiveTab(actionObj.tab);
           }, 1500); // Wait 1.5s for user to see the message before navigation
         }
      }`;

content = content.replace(receiveLogicRegex, receiveLogicReplacement);

fs.writeFileSync('src/features/assistant/AssistantPage.tsx', content);
