import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { DataStory } from '../../types';
import {
  FileText,
  Sparkles,
  Download,
  Share2,
  Printer,
  CheckCircle2,
  AlertTriangle,
  TrendingUp,
  Clock,
  BarChart3,
  Layers,
  Send,
  Database,
} from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const { activeDataset, user, workspace, dataStories, saveDataStory, language, t } = useApp();
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeStory, setActiveStory] = useState<DataStory | null>(
    dataStories.length > 0 ? dataStories[0] : null
  );

  const handleGenerateStory = async () => {
    setIsGenerating(true);
    try {
      const res = await fetch('/api/reports/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          dataset: activeDataset,
          language,
        }),
      });
      const data = await res.json();
      if (data.story) {
        saveDataStory(data.story);
        setActiveStory(data.story);
      }
    } catch (err) {
      console.error('Report generation error:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportJson = () => {
    if (!activeStory) return;
    const blob = new Blob([JSON.stringify(activeStory, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Data_Story_${activeStory.id}.json`;
    link.click();
  };

  return (
    <div className="space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#393939] pb-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[11px] font-mono font-bold uppercase tracking-widest text-[#0f62fe]">
              IBM CARBON / DATA STORYTELLING & REPORTS
            </span>
          </div>
          <h2 className="text-xl sm:text-2xl font-bold text-[#f4f4f4] tracking-tight mt-1">{t.reports.title}</h2>
          <p className="text-xs sm:text-sm text-[#c6c6c6] mt-0.5">{t.reports.subtitle}</p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {activeStory && (
            <>
              <button
                onClick={handlePrint}
                className="carbon-btn-secondary text-xs font-mono font-bold gap-1.5"
                title="Print or Save PDF"
              >
                <Printer className="w-3.5 h-3.5 text-[#0f62fe]" />
                <span>Print / PDF</span>
              </button>
              <button
                onClick={handleExportJson}
                className="carbon-btn-secondary text-xs font-mono font-bold gap-1.5"
                title="Export JSON"
              >
                <Download className="w-3.5 h-3.5" />
                <span>JSON</span>
              </button>
            </>
          )}

          <button
            onClick={handleGenerateStory}
            disabled={isGenerating}
            className="carbon-btn-primary text-xs font-mono font-bold uppercase tracking-wider gap-2"
          >
            <Sparkles className={`w-3.5 h-3.5 ${isGenerating ? 'animate-spin' : ''}`} />
            <span>{isGenerating ? t.common.loading : t.reports.generateStory}</span>
          </button>
        </div>
      </div>

      {/* Main Report View */}
      {activeStory ? (
        <div className="bg-[#262626] border border-[#393939] p-6 sm:p-8 space-y-6">
          {/* Story Meta Header */}
          <div className="border-b border-[#393939] pb-5 space-y-2">
            <div className="flex items-center gap-2">
              <span className="carbon-tag-blue uppercase text-[10px]">
                {activeDataset.format.toUpperCase()} Dataset Story
              </span>
              <span className="text-[11px] font-mono text-[#8d8d8d]">
                Generated on {new Date(activeStory.generatedAt).toLocaleDateString()}
              </span>
            </div>
            <h1 className="text-xl sm:text-2xl font-bold text-[#f4f4f4]">
              {language === 'ar' ? activeStory.titleAr || activeStory.title : activeStory.title}
            </h1>
            <p className="text-xs text-[#c6c6c6] font-mono">
              Dataset Context: <strong>{activeStory.datasetName}</strong> • Generated by {activeStory.author}
            </p>
          </div>

          {/* Executive Summary Block */}
          <div className="p-4 bg-[#161616] border-s-4 border-s-[#0f62fe] border border-[#393939] space-y-1">
            <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-[#33b1ff]">
              Executive Summary (الملخص التنفيذي)
            </h3>
            <p className="text-xs sm:text-sm text-[#f4f4f4] leading-relaxed">
              {language === 'ar' ? activeStory.executiveSummaryAr || activeStory.executiveSummary : activeStory.executiveSummary}
            </p>
          </div>

          {/* Sections Breakdown */}
          <div className="space-y-6">
            {activeStory.sections.map(section => (
              <div key={section.id} className="p-4 bg-[#1f1f1f] border border-[#393939] space-y-3">
                <h4 className="text-sm font-bold text-[#f4f4f4] flex items-center gap-2">
                  <span className="w-2 h-2 bg-[#0f62fe]" />
                  <span>{language === 'ar' ? section.titleAr || section.title : section.title}</span>
                </h4>
                <p className="text-xs text-[#c6c6c6] leading-relaxed">
                  {language === 'ar' ? section.narrativeAr || section.narrative : section.narrative}
                </p>

                {section.insights && section.insights.length > 0 && (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-2 border-t border-[#393939]">
                    {section.insights.map((ins, idx) => (
                      <div key={idx} className="p-2 bg-[#161616] border border-[#393939] flex items-start gap-2 text-xs">
                        <CheckCircle2 className="w-3.5 h-3.5 text-[#42be65] shrink-0 mt-0.5" />
                        <span className="text-[#f4f4f4]">{ins}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Strategic Recommendations */}
          {activeStory.recommendations && activeStory.recommendations.length > 0 && (
            <div className="p-5 bg-[#161616] border border-[#393939] space-y-3">
              <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-[#42be65] flex items-center gap-2">
                <TrendingUp className="w-4 h-4" />
                <span>Strategic Recommendations &amp; Next Actions</span>
              </h3>
              <div className="space-y-2">
                {activeStory.recommendations.map((rec, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs font-sans text-[#c6c6c6]">
                    <span className="w-4 h-4 bg-[#24a148]/20 text-[#42be65] font-mono text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5">
                      {i + 1}
                    </span>
                    <span>{rec}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="carbon-tile p-12 text-center text-[#c6c6c6]">
          <FileText className="w-12 h-12 text-[#0f62fe] mx-auto mb-3" />
          <p className="text-sm font-bold">No data story generated yet</p>
          <p className="text-xs text-[#8d8d8d] mt-1">
            Click &quot;Generate Data Story&quot; above to synthesize an automated executive analytics brief.
          </p>
        </div>
      )}
    </div>
  );
};
